### ISSUE TITLE
Design/Code Review 2

### ISSUE THREAD

**Issue by tvdmitrii** [SapphireStar31/recipe-searcher#6]
# Design/Code Review 2

@pawaitemadisoncollege As a meta comment, I was not sure what the bold rows in the table are for. I have assumed that these are headings for sections below and do not require input, but I could have been wrong.

I just wanted to put some of the things that stood out to me up front.
- Great job handling many-to-many relationships.
- I like the styled Cognito sign-up / login page. I did not know it is even possible.
- Very cool to see you using JavaScript for handling variable number of ingredients in a recipe, and then processing this list on the back end with Java.
- I like how you are using Spoonacular API to show similar recipes based on _user provided recipe name_. It adds a nice bit of interactivity.

#### Reviewer: Dmitrii Turygin

|Areas for Improvement|Criteria|Items Met or Exceeded|
|--------|---------|---------------|
||**Project effectively utilizes the technologies and techniques specified in the project objectives**||
| Some of the planned MVP functionality listed in user stories is missing. | Planned MVP Functionality | Revision Needed |
|| Logging framework used, i.e., no System.out.println() or printStacktrace() statements.| Met |
|| Hibernate used for all data access. | Met |
|| Authentication implemented and adds value to the application. | Met |
|| Consumes at least one web service or public api using Java. | Met |
| Create and read operations are present and accessible through the web app, however update and delete operations are missing. | Application is database-driven using full CRUD.| Revision Needed |
|| Database includes multiple one to many relationships. | Exceeded. Application handles multiple many-to-many relationships. |
|| Deployed to AWS for public access. | Met |
| Some form fields (like recipe name) could be marked as required. Maybe more server side user input validation. | Implements best practices (for example, data validation)  | Met |
|| **Synthesis of multiple concepts in unfamiliar situations requiring research beyond the scope of the class**||
||Experiments individually, exhibits independence and drive, shows originality in the solution.| Met |
||Implemented technologies or techniques not covered in course materials. | Met |
||**Code quality - Evaluate  code quality for the following and identify specific areas for improvement (class, method or line number). Be sure to list which code quality plugins/tools you used to assist with this analysis**||
|| Single-purpose methods | Met |
| Some minor things like putting Spoonacular API code into its own package, separating top level JSPs from fragments/templates. | Well-structured project| Met |
|| Descriptive naming of packages, classes, methods, variables | Met |
||Classes appropriately-sized  (no monster classes)| Met |
| Certain things could be further parameterized to reduce code duplication. For example, searching and listing recipes and ingredients are quite similar. Maybe these could be handled by a single JSP and servlet. | CPD (copy paste detection, meaning are the same lines of code repeated?| Met |
|| Are there candidates for super/subclass relationships, abstract classes, interfaces | Met |
| Maybe Spoonacular API base URL could also be a part of the spoonacularapi.properties. | Are any values hard-coded that should be in a properties file? | Met |
| There are a couple of places where exceptions would cause the user interface to crash. For example, SpoonacularAPIDao.searchAndGetResults() throws a runtime exception which is not caught in the servlet. Exceptions can also be caused by invalid input data. |Proper exception handling | Revision Needed |
||Proper error reporting to the user - custom error pages?| Met | 
| Some of the classes and methods are missing javadoc. Additional comments in the code could be helpful too. |Code documentation| Met | 
|| Is there code in the servlet doGet/doPost that should be refactored into testable classes or methods? | Met |
| As mentioned previously, some of the functionality related to searching and listing ingredients and recipes could be parameterized and consolidated. Some more styling with Bootstrap could go a long way. | Evaluate the JSPs for templating, data validation, overall look and feel.| Met |
|| JSPs use JSTL and EL, no java code | Met || |
|| Unit tests are truly a unit test rather than a high level functional test | Met | 
||Test data is appropriately cleaned up or handled| Met | 
| Test run with coverage was not performed, this was assessed visually. DAO is well tested. |There is full coverage of methods that perform business logic or utility functions| Met |
||Redundant code is eliminated by using set up and tear down methods, i.e., @Before, @After| Met |
||Other comments/notes?| |
||**Demonstrates initiative and thoughtful planning to leverage available resources (time, equipment, external expertise) to meet milestones and project objectives.** ||
|| **Evidence of significant revision and incorporation of feedback.** ||
| It was surprising to see such a high number of additions/deletions, however it appears that logs have been accidentally included into the repo and then later removed. Otherwise, the code has been continuously worked on throughout the semester. | What does github history and insights demonstrate about the work on this project?| Met |
|| **Project complexity** ||
| The project is more challenging than user display exercise. | Consider the user display exercise to be a simple project; how does this project compare? | Met |
| User authentication with Cognito, many-to-many relationships, consuming Spoonacular API, more complicated UI. | What aspects of the project add complexity? | Met |
|| **Additional Comments** ||

**Comment by pawaitemadisoncollege** [comment]
Hi @tvdmitrii - thank you for your thorough and thoughtful review. 

Your technique sharing what stood out to your before the getting into the review form provided a nice summary and starts the review on a positive note.  You used clear, concise language throughout, making it easy for @SapphireStar31 to understand what is on target and what could be better.  

In some cases it might be helpful to identify and link to specific examples  in the code, for example "SpoonacularAPIDao.searchAndGetResults() throws a runtime exception which is not caught in the servlet. Exceptions can also be caused by invalid input data.". This doesn't mean linking to every example, but providing and instance or two make it easy to jump to the exact location you are referring to at that point in time. 

This work shows you'll do well at similar reviews work this in industry - you do a good job evaluating the technical details while balancing kudos and areas for improvement.
